spring.application.name=lab02-nube

# Cargar variables desde archivo .env X NO usar .env en producción (Render no lo usa)
# spring.config.import=optional:file:.env.properties

# 🔹 DATABASE (Supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# 🔹 JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 🔹 SERVER (Render usa PORT)
server.port=${PORT:9090}

# 🔹 DEBUG
logging.level.org.springdoc=DEBUG
